receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 8192
    timeout: 5s
    send_batch_max_size: 10240

exporters:
  # Нативный прием OTLP метрик в VictoriaMetrics
  otlphttp/victoriametrics:
    endpoint: "http://victoria-metrics:8428/opentelemetry"
    tls:
      insecure: true

  # Нативный прием OTLP логов в VictoriaLogs
  otlphttp/victorialogs:
    endpoint: "http://victoria-logs:9428/insert/opentelemetry"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/victoriametrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/victorialogs]
